### ISSUE TITLE
Can't open my rails console after adding 'gcm' to Gemfile

### ISSUE THREAD

**Issue by shivakumaarmgs** [spacialdb/gcm#16]
```
/home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/gcm-0.0.9/lib/gcm.rb:5:in `<top (required)>': GCM is not a class (TypeError)
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `require'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `each'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `block in require'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `each'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `require'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.3/lib/bundler.rb:133:in `require'
	from /home/shivakumaarmgs/Rails/PCA/config/application.rb:15:in `<top (required)>'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:146:in `require'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:146:in `require_application_and_environment!'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/shivakumaarmgs/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by mckenn** [comment]
@shivakumaarmgs Facing exactly the same issue.

**Comment by mckenn** [comment]
false alert. Conflict with pushmeup gem.

**Comment by kashif** [comment]
:relieved:

**Comment by shivakumaarmgs** [comment]
Even I was using Pushme up for APNS, I guess GCM would have had conflict with that. just now realized. closing this one.

**Comment by shivakumaarmgs** [comment]
@mckenn :+1:
